apiVersion: v1
kind: Namespace
metadata:
  name: private
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment-processor
  name: payment-processor
  namespace: private
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-processor
  template:
    metadata:
      labels:
        app: payment-processor
    spec:
      containers:
        - name: payment-processor
          image: quay.io/skupper/patient-portal-payment-processor
          ports:
            - containerPort: 8080
---
apiVersion: skupper.io/v2alpha1
kind: Site
metadata:
  name: private
  namespace: private
---
apiVersion: skupper.io/v2alpha1
kind: Connector
metadata:
  name: payment-processor
  namespace: private
spec:
  routingKey: payment-processor
  port: 8080
  selector: app=payment-processor
