name: sample
services:
  skupper-router:
    image: quay.io/skupper/skupper-router:main
    volumes:
      - ./config:/etc/skupper-router/config:z
    environment:
      QDROUTERD_CONF: "/etc/skupper-router/config/skrouterd.json"
      QDROUTERD_CONF_TYPE: "json"
    network_mode: host
  my-service:
    image: docker.io/envoyproxy/envoy:v1.29.2
    networks:
      - sample1
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./my-service/envoy.yaml:/tmp/envoy.yaml
    command:
      - -c /tmp/envoy.yaml
    security_opt:
      - label:disable
  my-tcp-service:
    image: docker.io/envoyproxy/envoy:v1.29.2
    networks:
      - sample1
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./my-tcp-service/envoy.yaml:/tmp/envoy.yaml
    command:
      - -c /tmp/envoy.yaml
    security_opt:
      - label:disable
  my-service-workload:
    image: nginxinc/nginx-unprivileged:stable-alpine
    ports:
      - 8888:8080
  my-tcp-service-workload:
    image: quay.io/skupper/iperf3
    ports:
      - 4201:5201
    command:
      - -s
networks:
  sample1:
