---
- name: Teardown patient-portal example
  hosts: all
  connection: local
  tasks:
    - name: Stop and remove the database container
      containers.podman.podman_container:
        name: database
        state: absent

    - name: Teardown the podman site
      skupper.v2.system:
        action: teardown
        platform: podman

    - name: Remove kubernetes namespace 
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ item }}"
        state: absent
        wait: true
      loop:
        - public
        - private
