---
- name: Skupper V2 Hello World Example using Ansible
  hosts: all
  connection: local
  tasks:
    - name: Create Kubernetes namespaces west and east
      kubernetes.core.k8s:
        name: "{{ item }}"
        api_version: v1
        kind: Namespace
        state: present
      loop:
        - west
        - east

    - name: Install cluster scoped Skupper 2.0.0 into Kubernetes
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('url', 'https://github.com/skupperproject/skupper/releases/download/2.0.0/skupper-cluster-scope.yaml', split_lines=False) }}"

    - name: Create resources on west namespace
      skupper.v2.resource:
        path: "{{ item }}"
        namespace: west
      loop:
        - https://raw.githubusercontent.com/skupperproject/skupper-example-yaml/refs/heads/v2/west/site.yaml
        - https://raw.githubusercontent.com/skupperproject/skupper-example-yaml/refs/heads/v2/west/listener.yaml
        - https://raw.githubusercontent.com/skupperproject/skupper-example-yaml/refs/heads/v2/west/frontend.yaml
    - name: Create resources on east namespace
      skupper.v2.resource:
        path: "{{ item }}"
        namespace: east
      loop:
        - https://raw.githubusercontent.com/skupperproject/skupper-example-yaml/refs/heads/v2/east/site.yaml
        - https://raw.githubusercontent.com/skupperproject/skupper-example-yaml/refs/heads/v2/east/connector.yaml
        - https://raw.githubusercontent.com/skupperproject/skupper-example-yaml/refs/heads/v2/east/backend.yaml

    - name: Generate an AccessToken to the west namespace
      skupper.v2.token:
        name: west-grant
        namespace: west
      register: result
    
    - name: Create AccessToken on east namespace
      skupper.v2.resource:
        def: "{{ result.token }}"
        namespace: east
