---
apiVersion: v1
kind: Namespace
metadata:
  name: public
---
apiVersion: skupper.io/v2alpha1
kind: Site
metadata:
  name: public
  namespace: public
spec:
  linkAccess: default
---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: database
  namespace: public
spec:
  routingKey: database
  port: 5432
  host: database
---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: payment-processor
  namespace: public
spec:
  routingKey: payment-processor
  port: 8080
  host: payment-processor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: quay.io/skupper/patient-portal-frontend
          env:
            - name: DATABASE_SERVICE_HOST
              value: database
            - name: DATABASE_SERVICE_PORT
              value: "5432"
            - name: PAYMENT_PROCESSOR_SERVICE_HOST
              value: payment-processor
            - name: PAYMENT_PROCESSOR_SERVICE_PORT
              value: "8080"
          ports:
            - containerPort: 8080