name: sample
services:
  skupper-router:
    image: quay.io/skupper/skupper-router:main
    volumes:
      - ./config:/etc/skupper-router/config:z
    environment:
      QDROUTERD_CONF: "/etc/skupper-router/config/skrouterd.json"
      QDROUTERD_CONF_TYPE: "json"
    network_mode: host
  my-service:
    image: quay.io/fgiorgetti/skupper-firewall-proxy
    environment:
      PORT_MAPPING: "8080:host.docker.internal:8080"
    networks:
      - sample1
    cap_add:
      - NET_ADMIN
      - NET_RAW
    extra_hosts:
      - host.docker.internal:host-gateway
  my-service-workload:
    image: nginxinc/nginx-unprivileged:stable-alpine
    ports:
      - 8888:8080
networks:
  sample1:
